name: finanzas_personales
# Cambiamos la descripción genérica por la real del proyecto
description: "Aplicación móvil para el control financiero de ingresos, gastos y deudas."

# Evita que el paquete se publique accidentalmente en pub.dev (es un proyecto académico/privado).
publish_to: 'none' 

# Versión de compilación de la aplicación.
version: 1.0.0+1

# Versión del SDK de Dart requerida para ejecutar el proyecto.
environment:
  sdk: ^3.12.2

# Dependencias principales que la aplicación necesita para funcionar en el celular.
dependencies:
  flutter:
    sdk: flutter

  # Iconos de estilo iOS (viene por defecto con Flutter).
  cupertino_icons: ^1.0.8
  
  # --- PAQUETE CLAVE DEL PROYECTO ---
  # Se agregó este paquete para manejar las peticiones HTTP (GET, POST, PUT, DELETE).
  # Es lo que permite que la aplicación se conecte y consuma la API construida en C#.
  http: ^1.6.0

# Dependencias que solo se utilizan en la fase de desarrollo y pruebas.
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Herramienta para revisar que el código cumpla con las buenas prácticas de programación.
  flutter_lints: ^6.0.0

# Configuración específica para el diseño en Flutter.
flutter:

  # Activa la tipografía e iconos de Material Design, los cuales usamos en las tarjetas, 
  # botones y menús de toda la interfaz gráfica.
  uses-material-design: true